### ISSUE TITLE
Wrong attribute name in events received from forwarded attributes

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/JTango#37]
When a java client subscribes to a forwarded attribute, the attribute name contained in the DeviceAttribute object (obtained from event.getValue() in TangoChangeEvent class for instance) from the events received, is the name of the root attribute instead of the name of the attribute the client subscribed to (unless the attributes have the same names of course).

The name is correct in the event generated just after the subscription (synchronous call).

This problem is generating issues with atkpanel for instance when trying to change the set value of a forwarded RW attribute (if the root attr and forwarded attr do not have the same names, and if the root attr can generate events (if it is polled for instance)).
Please note that there is a work-around in atkpanel because the problem occurs only when clicking on the arrows of the wheel switch widget. If the user clicks on the set value and edit it by hand, typing the new set value with the keyboard without using the arrows, the write will work as expected.
When using the arrows, atkpanel will send an attribute write command with the wrong attribute name, resulting in an exception because the attribute does not exist, or resulting in writing the wrong attribute if an attribute of the same name as the root attribute exists and is different than the forwarded attribute.

This problem is not present in the C++ clients.

**Comment by Ingvord** [comment]
The name of the forwarded attribute is expected here not the root one - Do I get it right?

**Comment by bourtemb** [comment]
The name of the forwarded attribute, yes. The one the user subscribed to.

**Comment by Ingvord** [comment]
Interesting enough is that I can not subscribe to an event using JTango-9.3.3-SNAPSHOT: server output:

```
Host name/address cannot be determined !
```

Looks like this is due to [this method (HostInfo#checkInetAddress)](https://github.com/tango-controls/JTango/blob/master/tangorb/common/src/main/java/fr/esrf/TangoApi/HostInfo.java#L151)

Basically it fails to set proper host info when host name equals to IP address... In overall HostInfo implementation seems strange to me:
1) singleton
2) actual info depends on NI order (the last one always win, which might not be the desired behavior)
3) uses undocumented `trace` flag instead of logging framework

Here is my test project: [link](https://github.com/Ingvord/jtango-37)

**Comment by Ingvord** [comment]
@bourtemb Hi, I can not reproduce this one in my [test project](https://github.com/Ingvord/jtango-37). The client returns proper attribute name - _fwd-attr_. Which version of JTango you are using?

**Comment by bourtemb** [comment]
Hum... This is getting interesting...
I reproduced the problem with your test project and JTango 9.3.2 from bintray, but when the client subscribes to C++ Tango devices instead of the devices from the java servers you provided.
It seems to work as expected with the java servers you provided.

**Comment by bourtemb** [comment]
This issue seems to be still there in JTango 9.6.6
