### ISSUE TITLE
Exported feild shows wrong status

### ISSUE THREAD

**Issue by RajasGujarathi** [tango-controls/JTango#56]
![capture1](https://user-images.githubusercontent.com/31616516/38934455-6c4305f8-4339-11e8-8fea-ac06526c8478.JPG)
![capture2](https://user-images.githubusercontent.com/31616516/38934459-6d638232-4339-11e8-9fea-a2283702096b.JPG)
![capture3](https://user-images.githubusercontent.com/31616516/38934461-6dc5526e-4339-11e8-9717-fd1ca92a8fed.JPG)

Many times it so happens that the DS is not running, however, the exported field is seen as "true" in Jive.

**Comment by gwen-soleil** [comment]
Generally, if a DS is still flagged as exported, it is because the process has not been killed properly (i.e. kill -9). The DS will be flagged as unexported only during a proper shutdown (i.e. kill with astor). The reason is that this flag is set by the DS in the tango database by sending a command to the database device during its shutdown.

Have you got a scenario to reproduce this behavior?
