### ISSUE TITLE
Do we want travis to make GitHub release draft?

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/JTango#84]
As in #68 Travis performs JTango fat jar upload to GutHub releases and sets the release state to `draft` meaning that we have to set it to release manually once fat jar is uploaded.

Is this behaviour OK?

OR 

we must change it so that Travis do not change release state?

@bourtemb , @gwen-soleil , what do you think?

**Comment by bourtemb** [comment]
> As in #68 Travis performs JTango fat jar upload to GutHub releases and sets the release state to `draft` meaning that we have to set it to release manually once fat jar is uploaded.
> 
> Is this behaviour OK?

@ingvord, this behaviour sounds reasonable to me.

**Comment by Ingvord** [comment]
Well, looks like to me it is better if travis does as much job as possible. For instance, 9.5.18 was in draft when TangoSourceDistribution was building (https://travis-ci.org/tango-controls/TangoSourceDistribution/builds/617210418) hence failed

**Comment by bourtemb** [comment]
> Well, looks like to me it is better if travis does as much job as possible. For instance, 9.5.18 was in draft when TangoSourceDistribution was building (https://travis-ci.org/tango-controls/TangoSourceDistribution/builds/617210418) hence failed

It failed because of the way TangoSourceDistribution is getting the jar file (From the Github release download page).
The build you mentioned failed because the JTango version TangoSourceDistribution tried to use was not yet officially released. Should we allow this kind of things? It might be useful to test some release candidates indeed.
So what you propose would be to have Travis create a new release for each created tag;
this release would no longer be created in draft mode as now but would be a "pre-release" automatically?
This means that users subscribing to release notifications on this repository will be automatically notified immediately every time a tag is created?

The text in the release description might not be optimal immediately but could be changed later in the future.

Another approach would be to do something similar in the TangoSourceDistribution as what was done with cppTango where the cppTango git repository is cloned for a specific tag.
We could do the same with JTango and build the jar from the source code corresponding to the specific tag instead of just downloading the jar file from the github release download page. This would be heavier of course.

Let's see what the other are thinking?
