### ISSUE TITLE
[refactoring] Add types to Vectors in dao and consider migrating to List

### ISSUE THREAD

**Issue by altavir** [tango-controls/JTango#94]
Many classes in JTango core utilize Java 1.2 Vector class without generic type. In order to provide better type safety and refactoring possibilities, we need to add explicit types wherever possible. Also, Vector itself is obsolete and should be replaced by `List` in all cases, where thread safety is not an issue (and it does not seem to be the case in JTango core). `ArrayList` is better optimized for performance.

**Comment by KrystianKedron** [comment]
Dear Team,
I do my best to refactor the JTango code and get rid of using the Vector.
Also, I try to provide unit tests for the code that I change.
The common package was fully refactored in the context of the removal of Vector. 
In dao (TangoORB) package I refactor only the **fr.esrf.TangoApi** package, because in **fr.esrf.TangoDs** all classes that used the Vector collection are deprecated and not use in the different JTango packages (correct me if I'm wrong). 
After merging the #119 I think we can close this issue.

**Comment by gwen-soleil** [comment]
Yes!
